### ISSUE TITLE
Not possible

### ISSUE THREAD

**Issue by KrashKrash** [ryu878/MT5-python-bot#1]
Can't do pip install Metatrader5 on linux

**Comment by ryu878** [comment]
Hola! I read somewhere that it is possible to run mt5 in linux using wine. But I didn't tried it.
I have virtualbox with win10 for that. So first you have to install MetaTrader software, then pip install metatrader5.

**Comment by KrashKrash** [comment]
> Hola! I read somewhere that it is possible to run mt5 in linux using wine. But I didn't tried it.
> I have virtualbox with win10 for that. So first you have to install MetaTrader software, then pip install metatrader5.

Did that. Didn't work either. 😭
